WITH RECURSIVE ECOLI_GENERATION AS (
    -- 1. Anchor: 첫 세대 찾기
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    -- 3. UNION ALL
    UNION ALL
    
    -- 2. Recursive Part: 다음 세대 찾기
    SELECT C.ID, C.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA C
    JOIN ECOLI_GENERATION P ON P.ID = C.PARENT_ID
)

SELECT COUNT(EG.ID) AS COUNT, EG.GENERATION
FROM ECOLI_GENERATION EG
    LEFT JOIN ECOLI_DATA E ON EG.ID = E.PARENT_ID
WHERE E.PARENT_ID IS NULL
GROUP BY EG.GENERATION
ORDER BY EG.GENERATION;