WITH EMP_SCORES AS (
    SELECT EMP_NO,
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT ES.SCORE,
    HE.EMP_NO,
    HE.EMP_NAME,
    HE.POSITION,
    HE.EMAIL
FROM EMP_SCORES ES
    JOIN HR_EMPLOYEES HE ON ES.EMP_NO = HE.EMP_NO
WHERE ES.SCORE = (
        SELECT MAX(SCORE)
        FROM EMP_SCORES
    );